version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./:/app
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis:/etc/redis
volumes:
  redis:
